# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	#requires vagrant-disksize plugin - can only increase size
	#it can't shrink it so the below will throw a warning
	#so the following line is wrong
	config.disksize.size = "10GB"
	config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
     vb.name = "docker-vm"
	end
	config.vm.define "docker-vm" do |config|
	config.vm.box = "bento/ubuntu-18.04"
	config.vm.hostname = "docker-test"
	config.vm.network "public_network"
	config.vm.synced_folder "./code", "/home/vagrant/code"
	
	end
	#For tips visit https://technology.amis.nl/2019/03/23/6-tips-to-make-your-life-with-vagrant-even-better/
	#option 1 of docker install (built in docker provider)
	#requires vagrant-docker-compose plugin
	config.vm.provision :docker
	config.vm.provision :docker_compose
	#option 2 of docker instal (custom shell script)
	#you'll need to have the docker.sh script in the same directory as this Vagrantfile
	#config.vm.provision "shell", path: "docker.sh", run: "once"
end
