"""added resource type to inventoryresource

Revision ID: 9aa190353071
Revises: c0d1ded27422
Create Date: 2020-04-11 16:29:47.061065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa190353071'
down_revision = 'c0d1ded27422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_to_resource', sa.Column('resource_type', sa.Enum('wood', 'ore', 'ingot', name='resourcetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_to_resource', 'resource_type')
    # ### end Alembic commands ###
