"""updated work with proficiency tracking"

Revision ID: af5395424934
Revises: c8cc69374248
Create Date: 2020-04-11 20:02:42.226554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5395424934'
down_revision = 'c8cc69374248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('learning_speed', sa.SMALLINT(), nullable=True))
    op.add_column('worker', sa.Column('prof_ingot_next_level', sa.SMALLINT(), nullable=True))
    op.add_column('worker', sa.Column('prof_ore_next_level', sa.SMALLINT(), nullable=True))
    op.add_column('worker', sa.Column('prof_wood_next_level', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'prof_wood_next_level')
    op.drop_column('worker', 'prof_ore_next_level')
    op.drop_column('worker', 'prof_ingot_next_level')
    op.drop_column('worker', 'learning_speed')
    # ### end Alembic commands ###
