"""added proficiency stats to workers

Revision ID: c8cc69374248
Revises: 9aa190353071
Create Date: 2020-04-11 18:54:13.066600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cc69374248'
down_revision = '9aa190353071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('proficiency_ingot', sa.Float(), nullable=True))
    op.add_column('worker', sa.Column('proficiency_ore', sa.Float(), nullable=True))
    op.add_column('worker', sa.Column('proficiency_wood', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'proficiency_wood')
    op.drop_column('worker', 'proficiency_ore')
    op.drop_column('worker', 'proficiency_ingot')
    # ### end Alembic commands ###
