"""db changes for smelter job type

Revision ID: 0cdd600b8446
Revises: af5395424934
Create Date: 2020-04-12 20:50:10.443780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdd600b8446'
down_revision = 'af5395424934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('assigned_to_smelter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'assigned_to_smelter')
    # ### end Alembic commands ###
