"""updated land table

Revision ID: 11ea6bcf385f
Revises: 
Create Date: 2020-04-10 18:32:51.775012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ea6bcf385f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_node', sa.Column('maximum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_node', 'maximum')
    # ### end Alembic commands ###
