"""added uses and cd to land table

Revision ID: 793dd30c9f33
Revises: 11ea6bcf385f
Create Date: 2020-04-10 18:56:55.008177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793dd30c9f33'
down_revision = '11ea6bcf385f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('cooldown', sa.SMALLINT(), nullable=True))
    op.add_column('land', sa.Column('lifetime_uses', sa.Integer(), nullable=True))
    op.add_column('land', sa.Column('next_action', sa.DateTime(), nullable=True))
    op.add_column('land', sa.Column('temp_uses', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land', 'temp_uses')
    op.drop_column('land', 'next_action')
    op.drop_column('land', 'lifetime_uses')
    op.drop_column('land', 'cooldown')
    # ### end Alembic commands ###
