"""added density to land to give chance of failure for search"

Revision ID: c0d1ded27422
Revises: 793dd30c9f33
Create Date: 2020-04-10 19:06:51.188106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d1ded27422'
down_revision = '793dd30c9f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('land', sa.Column('density', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('land', 'density')
    # ### end Alembic commands ###
