"""base migration

Revision ID: e6eb8a2bcda7
Revises: 
Create Date: 2020-04-08 23:25:22.736500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6eb8a2bcda7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('promote_base', sa.Integer(), nullable=True))
    op.add_column('worker', sa.Column('promote_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'promote_cost')
    op.drop_column('worker', 'promote_base')
    # ### end Alembic commands ###
